version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: community-trip-db-test
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '5433:5432'
